package hu.mudlee.core.render.mesh;

import hu.mudlee.core.render.VertexBufferLayout;
import hu.mudlee.core.render.VertexLayoutAttribute;
import hu.mudlee.core.render.types.ShaderTypes;

/** Helpers for building the first colored unit cube entirely from generated vertices. */
public final class CubeMesh {

    private static final int FLOATS_PER_VERTEX = 7;
    private static final int STRIDE = FLOATS_PER_VERTEX * Float.BYTES;

    private CubeMesh() {}

    public static Mesh3D createColoredUnitCube() {
        return new Mesh3D(vertices(), indices(), layout());
    }

    public static VertexBufferLayout layout() {
        return new VertexBufferLayout(
                new VertexLayoutAttribute(0, 3, ShaderTypes.FLOAT, false, STRIDE, 0),
                new VertexLayoutAttribute(1, 4, ShaderTypes.FLOAT, false, STRIDE, 3 * Float.BYTES));
    }

    public static float[] vertices() {
        return new float[] {
            // Front (+Z), red
            -0.5f,
            -0.5f,
            0.5f,
            1f,
            0f,
            0f,
            1f,
            0.5f,
            -0.5f,
            0.5f,
            1f,
            0f,
            0f,
            1f,
            0.5f,
            0.5f,
            0.5f,
            1f,
            0f,
            0f,
            1f,
            -0.5f,
            0.5f,
            0.5f,
            1f,
            0f,
            0f,
            1f,
            // Back (-Z), cyan
            0.5f,
            -0.5f,
            -0.5f,
            0f,
            1f,
            1f,
            1f,
            -0.5f,
            -0.5f,
            -0.5f,
            0f,
            1f,
            1f,
            1f,
            -0.5f,
            0.5f,
            -0.5f,
            0f,
            1f,
            1f,
            1f,
            0.5f,
            0.5f,
            -0.5f,
            0f,
            1f,
            1f,
            1f,
            // Left (-X), green
            -0.5f,
            -0.5f,
            -0.5f,
            0f,
            1f,
            0f,
            1f,
            -0.5f,
            -0.5f,
            0.5f,
            0f,
            1f,
            0f,
            1f,
            -0.5f,
            0.5f,
            0.5f,
            0f,
            1f,
            0f,
            1f,
            -0.5f,
            0.5f,
            -0.5f,
            0f,
            1f,
            0f,
            1f,
            // Right (+X), magenta
            0.5f,
            -0.5f,
            0.5f,
            1f,
            0f,
            1f,
            1f,
            0.5f,
            -0.5f,
            -0.5f,
            1f,
            0f,
            1f,
            1f,
            0.5f,
            0.5f,
            -0.5f,
            1f,
            0f,
            1f,
            1f,
            0.5f,
            0.5f,
            0.5f,
            1f,
            0f,
            1f,
            1f,
            // Top (+Y), blue
            -0.5f,
            0.5f,
            0.5f,
            0f,
            0f,
            1f,
            1f,
            0.5f,
            0.5f,
            0.5f,
            0f,
            0f,
            1f,
            1f,
            0.5f,
            0.5f,
            -0.5f,
            0f,
            0f,
            1f,
            1f,
            -0.5f,
            0.5f,
            -0.5f,
            0f,
            0f,
            1f,
            1f,
            // Bottom (-Y), yellow
            -0.5f,
            -0.5f,
            -0.5f,
            1f,
            1f,
            0f,
            1f,
            0.5f,
            -0.5f,
            -0.5f,
            1f,
            1f,
            0f,
            1f,
            0.5f,
            -0.5f,
            0.5f,
            1f,
            1f,
            0f,
            1f,
            -0.5f,
            -0.5f,
            0.5f,
            1f,
            1f,
            0f,
            1f,
        };
    }

    public static int[] indices() {
        return new int[] {
            0, 1, 2, 0, 2, 3,
            4, 5, 6, 4, 6, 7,
            8, 9, 10, 8, 10, 11,
            12, 13, 14, 12, 14, 15,
            16, 17, 18, 16, 18, 19,
            20, 21, 22, 20, 22, 23
        };
    }
}
